# Generated by Django 4.2.30 on 2026-07-15 13:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('usuarios', '0002_institucioneducativa_rol_alter_usuario_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='EducacionNivel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150, unique=True, verbose_name='nombre')),
                ('minutos_periodo', models.PositiveIntegerField(verbose_name='minutos por período pedagógico')),
                ('periodos_minimos_semana', models.PositiveIntegerField(verbose_name='períodos pedagógicos mínimos semanales')),
            ],
            options={
                'verbose_name': 'nivel educativo',
                'verbose_name_plural': 'niveles educativos',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='EducacionSubNivel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150, unique=True, verbose_name='nombre')),
                ('minutos_periodo', models.PositiveIntegerField(verbose_name='minutos por período pedagógico')),
                ('periodos_minimos_semana', models.PositiveIntegerField(verbose_name='períodos pedagógicos mínimos semanales')),
                ('nivel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subniveles', to='planificacion.educacionnivel', verbose_name='nivel educativo')),
            ],
            options={
                'verbose_name': 'subnivel educativo',
                'verbose_name_plural': 'subniveles educativos',
                'ordering': ['nivel__nombre', 'nombre'],
            },
        ),
        migrations.CreateModel(
            name='PlanEstudio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200, verbose_name='nombre')),
                ('estado', models.CharField(choices=[('VIGENTE', 'Vigente'), ('NO_VIGENTE', 'No vigente')], default='NO_VIGENTE', max_length=20, verbose_name='estado')),
                ('institucion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='planes_estudio', to='usuarios.institucioneducativa', verbose_name='institución educativa')),
            ],
            options={
                'verbose_name': 'plan de estudio',
                'verbose_name_plural': 'planes de estudio',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='GradoEscolar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150, verbose_name='nombre')),
                ('orden', models.PositiveIntegerField(verbose_name='orden')),
                ('nivel', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='grados_escolares', to='planificacion.educacionnivel', verbose_name='nivel educativo')),
                ('plan_estudio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grados_escolares', to='planificacion.planestudio', verbose_name='plan de estudio')),
                ('subnivel', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='grados_escolares', to='planificacion.educacionsubnivel', verbose_name='subnivel educativo')),
            ],
            options={
                'verbose_name': 'grado escolar',
                'verbose_name_plural': 'grados escolares',
                'ordering': ['orden', 'nombre'],
            },
        ),
        migrations.CreateModel(
            name='Asignatura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150, verbose_name='nombre')),
                ('periodos_minimos_semana', models.PositiveIntegerField(verbose_name='períodos pedagógicos mínimos semanales')),
                ('grado_escolar', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asignaturas', to='planificacion.gradoescolar', verbose_name='grado escolar')),
            ],
            options={
                'verbose_name': 'asignatura',
                'verbose_name_plural': 'asignaturas',
                'ordering': ['nombre'],
            },
        ),
    ]
