# Generated by Django 4.2.30 on 2026-07-10 16:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='InstitucionEducativa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200, verbose_name='nombre')),
                ('codigo', models.CharField(max_length=20, unique=True, verbose_name='código')),
                ('ruc', models.CharField(max_length=20, unique=True, verbose_name='ruc')),
            ],
            options={
                'verbose_name': 'institución educativa',
                'verbose_name_plural': 'instituciones educativas',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Rol',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(choices=[('ADMINISTRADOR', 'Administrador'), ('AUTORIDAD_ACADEMICA', 'Autoridad académica'), ('DOCENTE', 'Docente'), ('SECRETARIA', 'Secretaria'), ('ESTUDIANTE', 'Estudiante'), ('DECE', 'DECE')], max_length=50, unique=True, verbose_name='nombre del rol')),
                ('requiere_institucion', models.BooleanField(default=False, verbose_name='requiere institución')),
            ],
            options={
                'verbose_name': 'rol',
                'verbose_name_plural': 'roles',
                'ordering': ['nombre'],
            },
        ),
        migrations.AlterModelOptions(
            name='usuario',
            options={'ordering': ['first_name', 'last_name'], 'verbose_name': 'usuario', 'verbose_name_plural': 'usuarios'},
        ),
        migrations.CreateModel(
            name='UsuarioRol',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activo', models.BooleanField(default=True, verbose_name='activo')),
                ('fecha_inicio', models.DateField(verbose_name='fecha de inicio')),
                ('fecha_fin', models.DateField(blank=True, null=True, verbose_name='fecha de fin')),
                ('institucion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='autoridades', to='usuarios.institucioneducativa', verbose_name='institución educativa')),
                ('rol', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='usuario_rol_instances', to='usuarios.rol', verbose_name='rol')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usuario_rol_instances', to=settings.AUTH_USER_MODEL, verbose_name='usuario')),
            ],
            options={
                'verbose_name': 'asignación de rol',
                'verbose_name_plural': 'asignaciones de rol',
                'ordering': ['-fecha_inicio'],
            },
        ),
    ]
